### ISSUE TITLE
listview produces various glitches when native scrolling is used (Android 4.1/4.2)

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-ui-core#152]
Discussed in 834380. 

Removing certain 3d transforms fixes it: 

```css
    .km-on-android.km-4 .km-native-scroller .km-listview-wrapper {
      -webkit-transform: none;
    }
```

I could not reproduce the problem on the Nexus S device, only in the emulators.
