### ISSUE TITLE
Button's Icon has incorrect position and opacity when added in TabStrip

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#1759]
[http://dojo.telerik.com/aREXu](http://dojo.telerik.com/aREXu)

Ticket: 1038309

Workaround is available in this dojo—[http://dojo.telerik.com/aREXu/3](http://dojo.telerik.com/aREXu/3)

````CSS
.k-tabstrip .k-button .k-icon.[iconClass],
.k-tabstrip .k-button:hover .k-icon.[iconClass]{
  background-position: -64px -80px;
  opacity: .4;
}
````
