### ISSUE TITLE
Different top/bottom and left/right padding in TabStrip content

### ISSUE THREAD

**Issue by yordanov** [telerik/kendo-ui-core#1965]
E.g. in Default theme the content padding is:
```css
.k-tabstrip > .k-content {
  padding: .3em .92em;
}
```
It should be equal on all sides:
```css
.k-tabstrip > .k-content {
  padding: .92em;
}
```

Please review all themes.
