### ISSUE TITLE
Transitions cause full view flicker in iOS / Cordova

### ISSUE THREAD

**Issue by petyosi** [telerik/kendo-ui-core#239]
Details available here: 846606 . Seems related to backface visibility setting, as this resolves it in a simpler test case: 

``` css
.km-content, .km-root, .km-view, .km-pane {
            -webkit-backface-visibility: hidden;
}
```

Maybe we need to apply it to all transitioning elements.
