### ISSUE TITLE
Dialog's title is hidden with Nova theme

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2714]
### Bug report
The Nova theme breaks the Dialogs styles.

### Reproduction of the problem
http://dojo.telerik.com/IlUXA

### Current behavior

![image](https://cloud.githubusercontent.com/assets/4222379/22555466/72d54462-e96c-11e6-9682-9112b1f2f2c6.png)

### Expected/desired behavior
Check design. This is onlly an example
![image](https://cloud.githubusercontent.com/assets/4222379/22555484/81218f1c-e96c-11e6-8f37-103466c07915.png)

### Workaround

```css
      .k-dialog .k-window-titlebar {
            padding: .6em .8em 1em .8em;
      }
    
      .k-dialog .k-window-titlebar .k-dialog-title {
        padding: 0;
        font-size:1.2em;
      }
```

### Environment

* **Kendo UI version:** 2017.1.118
* **jQuery version:** any
* **Browser:** [all  ]
