### ISSUE TITLE
There is no right padding in sheet tab when there is single one

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-ui-core#2736]
### Bug report

The visual issue is visible in this demo: http://demos.telerik.com/kendo-ui/spreadsheet/index. 

![image](https://cloud.githubusercontent.com/assets/4222379/22690898/87e92b66-ed40-11e6-83e4-03c5aefd5654.png)

Comes from: https://github.com/telerik/kendo/commit/fefac3dacb3a33911732d157b0029a0b0a1683f0

### Expected/desired behavior

![image](https://cloud.githubusercontent.com/assets/4222379/22690923/a00cec82-ed40-11e6-835b-90b45ca2e02c.png)

### Workaround

```css
  .k-spreadsheet-sheets-bar span.k-link:first-child{
  padding: .65em .92em;
}
.k-spreadsheet-sheets-bar .k-spreadsheet-sheets-remove{
  margin-left: -.5em;
}
```

### Environment

* **Kendo UI version:** 2017.1.118
* **Browser:** [all  ]
