### ISSUE TITLE
Non-text Image Button image not centered vertically

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-ui-core#3335]
### Description
The image inside a image button with no text is not centered. 

See this dojo: http://dojo.telerik.com/enefU/7
Also reproducible in Toolbar ([dojo](http://dojo.telerik.com/OCICi)).

Reported in ticket 1115055.
### Screenshot
![image_button_vertical](https://user-images.githubusercontent.com/5155721/27370786-d1c18de8-5666-11e7-85c4-0dae04817d07.png)

### Possible fix
Add the following CSS rule:
```CSS
.k-button-icon .k-image {
    vertical-align: text-top;
}
```

similar issue: https://github.com/telerik/kendo-ui-core/issues/935
