### ISSUE TITLE
Grid Pager numbers cover bottom Grid row preventing selection on small screens for Bootstrap, Fiori, Flat, and Office365 themes.

### ISSUE THREAD

**Issue by theOrlin** [telerik/kendo-ui-core#3387]
### Description
The Grid pager on smaller screens (<1024px) has a `transform:translateY` set and in effect covers the bottom Grid row preventing selection when selection is enabled.

![grid_pager](https://user-images.githubusercontent.com/5155721/27957522-8a9565c0-6327-11e7-96c2-310abc8635c1.png)

### Example
http://dojo.telerik.com/OlApO 
### Scope
Observable in **Default** types, **Bootstrap**, **Fiori**, and **Office365** themes

### Possible fix
```CSS
    @media only screen and (max-width: 1024px) {
      .k-grid .k-pager-numbers:not(.k-state-expanded) {
        transform: none;
      }
      .k-grid .k-pager-numbers:not(.k-state-expanded) .k-current-page {
        transform: none;
      }
    }
```

_Reported in ticket 1118200_
