### ISSUE TITLE
REGRESSION: Why would you now align kendo.ui.Dialog buttons to the left (normal layout)?

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-ui-core#3603]
### Bug report

Since v2017.3.913 kendo.ui.Dialog buttons are now aligned to the left when buttonLayout === "normal". Besides round corners have been removed between buttons.

This breaks visual consistency with other dialogs in kendo.ui.Editor, kendo.ui.Gantt, kendo.ui.SpreadSheet.

### Reproduction of the problem

See http://dojo.telerik.com/uGADe. 

![image](https://user-images.githubusercontent.com/2556751/30652857-607de3fe-9e21-11e7-94c2-2e5c84fceb6a.png)

### Current behavior

Buttons aligned to the left and round corners removed between buttons.

### Expected/desired behavior

Buttons aligned to the right and round corners on all sides of buttons like in other dialogs from kendo.ui.Editor, kendo.ui.Gantt, kendo.ui.SpreadSheet.

### Environment

* **Kendo UI version:** 2017.3.913
* **jQuery version:** x.y
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jlchereau** [comment]
You need:

```less
.k-dialog {
    .k-dialog-buttongroup {
        &.k-dialog-button-layout-normal {
            display: flex;
            justify-content: flex-end;
           .k-button {
               border-radius: @border-radius @border-radius @border-radius @border-radius;
           }
        }
    }
}
```
