### ISSUE TITLE
Overwritten TabStrip background color by Dialog styles

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-ui-core#3635]
### Bug report

http://dojo.telerik.com/asEBiZ

### Reproduction of the problem
1. Remove the workaround

``` css 
<style>
    .k-tabstrip {
      background-color: #3f51b5 !important;
    }
  </style>
```
2. Load the page

### Current behavior
.k-dialog .k-header {
    background: 0px 0px;
}
This style overrides the style of the tabstrip header and the prev next buttons are not visible.

### Expected/desired behavior
The prev next buttons are visible and the background color for the tabstrip is set.

### Environment

* **Kendo UI version:** 2017.3.913
* **Browser:** all
