### ISSUE TITLE
Remove legacy css from dataviz styles

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4251]
Based on customer report: the following legacy CSS is not needed, as it targets IE7

```css
.k-baseline-marker {
    zoom: 1;
    *display: inline; // <- this is not needed
}
```

TID: 1168761
