### ISSUE TITLE
Erroneous calculation in card layout

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4252]
Based on customer report: in card/layout there is erroneous calculation that does not yields product, but the expression itself:

```less
.k-card-title + .k-card-subtitle {
    margin-top: -( @card-title-margin-bottom * .75 ); // move the minus sign inside the braces
}
```

TID: 1168761
