### ISSUE TITLE
Less themes with opacity icons have issues on hover / focus

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-ui-core#4303]
If a given less theme, say material, has icons with opacity (like in the grid pager), in certain cases when the parent widget is focused, the icons light up.

See this dojo: https://dojo.telerik.com/@joneff/IweSEYEh. Just click in the window and it gets focused. There is a rule `.k-state-focused .k-icon {opacity: 1}` that causes the issue.

TID: 1151151

**Comment by joneff** [comment]
A quick workaround is:

```css
.k-icon {
    opacity: 1;
}
/* Or if that doesn't work */
.k-button .k-icon,
.k-widget .k-icon {
    opacity: 1;
}
```

But that resets the opacity of all icons to 1 and is not an elegant solution
