### ISSUE TITLE
Clear selection button (X) is not visible in Metro theme

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-ui-core#4433]
### Bug report
Clear selection button (X) is not visible in Metro theme. **Regression since 2018.2.516**

### Reproduction of the problem
![image](https://user-images.githubusercontent.com/6614183/43896257-e3a19434-9be0-11e8-9324-089f5808d52c.png)

### Expected/desired behavior
The clear icon should be visible when selection is made:
![image](https://user-images.githubusercontent.com/6614183/43896293-00652ebe-9be1-11e8-8b6d-ab087f91903a.png)

### Environment
* **Kendo UI version:** 2018.2.620
* **Browser:** [all]

**Comment by veselints** [comment]
To workarownd this issue use the following CSS rule:
```CSS
.k-combobox .k-dropdown-wrap > span.k-icon.k-clear-value.k-i-close {
  color: #787878;
}
```
