### ISSUE TITLE
Input widgets not rendered correctly with form-control class inside input-group

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-ui-core#4654]
### Bug report

When Kendo UI input widgets are decorated with Bootstrap's form-control class and nested in .input-group, the widgets cannot be opened due to incorrect rendering.

Issue is caused by the float: left style:
```css
.input-group .form-control {
  float: left;
  ...
}
```

### Reproduction of the problem

[TelerikMvcAppComboInputgroup.zip](https://github.com/telerik/kendo-ui-core/files/2557862/TelerikMvcAppComboInputgroup.zip)

### Current behavior

Widgets are not rendered correctly and cannot be opened.

### Expected/desired behavior

Widgets should be rendered correctly with form-control class.

### Workaround

```css
<style>
  .input-group .k-widget.form-control,
  .input-group .k-widget.form-control .k-input {
    float: none;
  }
</style>
```

### Environment

* **Kendo UI version:** 2018.3.1017
* **Browser:** [all]
