### ISSUE TITLE
Chart Tooltip not showing when the select option is enabled

### ISSUE THREAD

**Issue by georgi-sla** [telerik/kendo-ui-core#6928]
### Bug report
When the select functionality is enabled, the tooltip does not show up when hovered.

### Reproduction of the problem

https://dojo.telerik.com/@georgi_slavov/ajINUMut 
Hover over the series

### Current behavior

The tooltip does not show.

### Expected/desired behavior

The tooltip should show. 

### Environment

* **Kendo UI version:** 2022.2.621
* **jQuery version:** 1.12.4
* **Browser:** [all]

**Comment by tsvetomir** [comment]
One possible workaround (IE11+) is to add the following style, [see demo](https://dojo.telerik.com/UcUwewav):
```css
.k-chart .k-selector,
.k-chart .k-selector .k-mask,
.k-chart .k-selector .k-selection,
.k-chart .k-selector .k-selection-bg
{
  pointer-events: none;  
}

.k-chart .k-selector .k-selection .k-handle
{
  pointer-events: auto;  
}
```

This disables the ability to drag the selection, only the handles can be used to adjust it.
